server:
  port: 8085

spring:
  application:
    name: email-service
  cloud:
    function:
      definition: newProductEvent
    stream:
      bindings:
        newProductEvent-in-0:
          destination: product-events
          group: email-service-group
          binder: rabbit
  rabbitmq:
    host: localhost
    port: 5672
